name: Запуск автотестов

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Install dependencies
        run: mvn clean install

      # Создаем директорию для результатов Allure
      - name: Create allure-results directory
        run: mkdir -p ./target/allure-results

      # Запускаем тесты с сохранением результатов в target/allure-results
      - name: Run tests and collect Allure results
        run: mvn clean test -Dallure.results.directory=./target/allure-results

      # Проверяем, что результаты тестов появились в директории
      - name: List allure-results directory
        run: ls -R ./target/allure-results

      # Генерируем Allure отчет
      - name: Generate Allure report
        run: mvn allure:report

      # Проверяем, что отчет сгенерирован
      - name: List Allure report directory
        run: ls -R ./target/site/allure-maven-plugin

      # Публикуем отчет на GitHub Pages
      - name: Deploy Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/site/allure-maven
          publish_branch: gh-pages