name: CI Pipeline

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Проверяем код из репозитория
      - name: Checkout code
        uses: actions/checkout@v3

      # Шаг 2: Устанавливаем JDK (например, JDK 17)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'

      # Шаг 3: Кэшируем зависимости Maven для ускорения следующих запусков
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Шаг 4: Компилируем проект с помощью Maven
      - name: Build with Maven
        run: mvn clean install

      # Шаг 5: Запускаем тесты
      - name: Run tests
        run: mvn test --no-transfer-progress

      # Шаг 6: Публикуем отчет Allure (опционально)
      - name: Publish Allure Report
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: target/allure-results
